apiVersion: skaffold/v2beta1
kind: Config
metadata:
  name: hello-kubernetes
build:
  local:
    useBuildkit: true
  artifacts:
    - image: shikanime/hello-kubernetes
      docker:
        dockerfile: examples/hello_kubernetes/Dockerfile
      context: ../../
deploy:
  kustomize:
    paths:
      - manifests
