apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  app.kubernetes.io/name: hello-kubernetes
  app.kubernetes.io/instance: hello-kubernetes
  app.kubernetes.io/version: "0.1.0"
  app.kubernetes.io/component: application
resources:
  - svc-headless.yaml
  - statefulset.yaml
